"""One-shot seed of docs/IDEA_TRACKER.xlsx from the project's full history.

Everything asked for Krishna since the project started, reconstructed from
BACKLOG.md plus the session record. Run once; after this, use tracker_io.add
/update as asks arrive.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import tracker_io

ROWS = [
    # (Ask, Detail, Status, Notes)
    ("Fully local voice companion (no cloud API at runtime)",
     "Core requirement behind the whole project: brain/voice never leave the machine.",
     "done", "Ollama + faster-whisper + Kokoro, all local. Verified."),
    ("Push-to-talk that stops when you stop speaking",
     "Not a fixed N-second window -- biggest 'not like a real conversation' complaint.",
     "done", "record_vad() using webrtcvad."),
    ("Streamlit UI instead of a bare terminal",
     "Chat history in a real window.", "done", "app.py"),
    ("Interrupt / barge-in support",
     "Press Enter mid-reply and Krishna stops talking.",
     "done", "Console only. Streamlit's single-threaded rerun model can't do it cleanly."),
    ("Persistent memory across sessions",
     "Remember previous conversations, not just the current one.",
     "done", "memory.json, loaded on start, saved every turn."),
    ("Safe notes capability",
     "Say 'note ...' / 'remember ...' -> appended to notes.md.",
     "done", "Plain string match + file append, no LLM decides what gets saved -- on purpose."),
    ("Talking-head avatar",
     "met4citizen/TalkingHead, 3D WebGL avatar with real lip-sync.",
     "done", "Lip-sync timing from Whisper on Krishna's OWN speech -- avoids their Google-Cloud-TTS timing path."),
    ("Fix: mouth moving when no one is speaking",
     "Any Streamlit rerun re-triggered speakAudio() on stale audio.",
     "done", "Turn-id gate: only the first render of a reply speaks."),
    ("Fix: TTS crash took the whole app down",
     "Kokoro G2P raised TypeError on certain text mid-reply.",
     "done", "Text sanitized + call wrapped; a TTS failure now goes unspoken instead of crashing."),
    ("In-app restart button to pick up code changes",
     "A page refresh doesn't reload krishna.py -- Python caches it on import.",
     "done", "supervisor.py relaunches; Restart button exits the process."),
    ("Voice picker",
     "Choose between Kokoro voices in the UI.",
     "done", "7 voices, each verified real by generating audio, not assumed from naming."),
    ("Tool-calling so Krishna knows things past its training cutoff",
     "Weather, currency, dictionary, jokes, news, stocks, sports.",
     "done", "Model decides when to call; tools.py. News still needs a key (separate row)."),
    ("Stop Krishna deflecting instead of stating real tool data",
     "Said 'I'm a god, not a weatherman' instead of the fetched temperature.",
     "done", "Explicit SYSTEM_PROMPT instruction to state tool results directly."),
    ("Stock prices",
     "Live quotes mid-conversation.",
     "done", "Finnhub; no reliable keyless source exists (Stooq dead, Yahoo fragile). Verified live on AAPL/TSLA/NVDA."),
    ("Sports scores",
     "Live/recent results mid-conversation.",
     "done", "TheSportsDB free published test key -- genuinely keyless, no signup. Verified live."),
    ("Multi-language support ('pick any language')",
     "Touches Whisper transcribe, Kokoro lang_code + voice sets, and TalkingHead lipsync.",
     "done", "7 languages verified end-to-end: English US/UK, French, Hindi, Spanish, Italian, Portuguese."),
    ("Avatar picker (more/better avatar faces)",
     "The one avatar (brunette.glb) was the only one available.",
     "done", "5 avatars now, incl. 2 photo-realistic (Avaturn, AvatarSDK). All verified rigged (ARKit+15 visemes+Mixamo)."),
    ("Background picker",
     "Fixed dark colour behind the avatar previously.",
     "done", "8 backgrounds (colours + gradients) in avatar_widget.py."),
    ("Photorealistic avatar via free GPU",
     "SadTalker on a free GPU; fallbacks across providers, not one path.",
     "done", "Working on Kaggle: real 855KB mp4, full GFPGAN pipeline, ~5 min on a free T4. 5 distinct root causes fixed."),
    ("Free-GPU fallback options researched",
     "Explicit ask for redundancy across providers.",
     "done", "Lightning AI best remaining (persistent env, ~22 GPU-hrs/mo, no CC); Saturn Cloud third. SageMaker Studio Lab closing -- skip."),
    ("Use the trading project's Finnhub key for now",
     "Rather than a new signup.",
     "done", "Pulled from NYSE_DATA vault into gitignored api_keys.env; key never printed; git-ignore verified."),

    # --- open ---
    ("Separate Finnhub key for Krishna",
     "Currently shares the trading bot's key, so both draw on one 60 calls/min free limit.",
     "pending", "Free second signup, then one line in api_keys.env. No code change."),
    ("News tool (Currents API)",
     "Last remaining live-data gap. Krishna currently says it can't get news.",
     "waiting_on_user", "Needs a free Currents API key."),
    ("Indian avatar face",
     "Explicitly asked for Indian faces.",
     "waiting_on_user", "Needs a correctly-rigged .glb. Avaturn/AvatarSDK (now installed) generate from a photo -- could produce one."),
    ("Telugu / Indian-accent voice",
     "Telugu needs a different engine entirely; Indian-accented English is a separate option.",
     "waiting_on_user", "AI4Bharat IndicF5 (Telugu) vs MeloTTS (Indian-accented English) -- which matters more?"),
    ("Gmail access",
     "Asked for 'all daily used' APIs including Gmail.",
     "waiting_on_user", "Different risk category -- OAuth into a real inbox, not a public lookup. Needs an explicit yes."),
    ("'Autonomous bot' scope clarification",
     "Does it act only when asked, or on its own?",
     "waiting_on_user", "Unanswered since the autonomy/control concern was raised."),
    ("Upgrade Kokoro -> Mandarin + Japanese",
     "Installed kokoro==0.2.2 never had these languages; latest is 0.7.16.",
     "pending", "~15-version jump; held back to avoid risking the verified English/avatar path."),
    ("Wire in Chatterbox TTS",
     "Installed and importable, never wired in to replace Kokoro.",
     "pending", "Blind study: 65.3% preferred Chatterbox Turbo over ElevenLabs."),
    ("Integrate SadTalker output into Krishna",
     "Now that it produces video, decide how/whether it fits live speaking.",
     "pending", "~5 min per render means it can't be live-conversational. Realistic use: pre-rendered clips."),
    ("Persistent avatar (no reload flicker per reply)",
     "components.html() makes a fresh iframe each reply.",
     "pending", "Needs a proper custom Streamlit component with iframe messaging."),
    ("Interrupt support in the Streamlit UI",
     "Works in console only.",
     "pending", "Structurally hard given Streamlit's rerun model."),
    ("Always-listening / wake-word mode",
     "Explicitly paused given the autonomy/control concern.",
     "pending", "Off by default if ever built; push-to-talk remains the norm."),
    ("Telegram integration",
     "Must NOT be bolted onto the live trading bot without its own careful conversation.",
     "pending", "Real financial stakes on that bot."),
    ("YouTube avatar content pipeline",
     "Separate goal from Krishna's live speaking.",
     "pending", "Explicitly backlogged by you in favour of live speaking first."),
    ("Open Interpreter on the laptop",
     "Dropped on the VM -- 2 cores too slow (hardware ceiling, verified).",
     "pending", "Would need its own Docker sandboxing since it'd run where real files live."),
]

for ask, detail, status, notes in ROWS:
    tracker_io.add(ask, detail=detail, status=status, notes=notes)

df = tracker_io.list_all()
print(f"seeded {len(df)} rows -> {tracker_io.PATH}")
print(df["Status"].value_counts().to_string())
